FROM node:14-alpine

WORKDIR /app

ENTRYPOINT ["npm"]

# docker run -it -v "D:\codes\Docker\utility container:/app" node:util npm init -y

# if its cmd instead of entrypoint, then any command written after image name will 
# replace the cmd in the dockerfile

# but in case of entry point it will add the word here it is "npm" in front of every command
# written after image name 

# docker run -it -v "D:\codes\Docker\utility container:/app" node:util init -y       after using entry point in dockerfile


